### ISSUE TITLE
Hide slider when inactive

### ISSUE THREAD

**Issue by franglais125** [TimurKiyivinski/gnome-shell-night-light-slider-extension#1]
Nice extension! I happened to suggest this to someone on reddit, and they noted that it would be more sensible if the temperature slider were hidden while the Night Light is not activated.

**Comment by kiyui** [comment]
Hmm, seems reasonable considering most people do not have it on 24/7 like I do 😁  I'll look into it~

**Comment by franglais125** [comment]
Heh, sounds good, thanks!

**Comment by kiyui** [comment]
Fixed in latest commit, will publish changes once I complete the preferences feature~

**Comment by franglais125** [comment]
Sounds great, thanks!
