### ISSUE TITLE
parallel sliders

### ISSUE THREAD

**Issue by corebots** [TimurKiyivinski/gnome-shell-night-light-slider-extension#10]
hi, since a few days maybe weeks, i keep seing this all the time with your extension (remains the same across shell themes).. when i move one and release it, other two slide into the same position. i'm on Fedora 27. 
![2017-10-31_20-48-09_931](https://user-images.githubusercontent.com/12252430/32246019-f2390248-be7d-11e7-9e05-55d4a685ada6.jpg)

**Comment by kiyui** [comment]
That's a very interesting find, I will need a bit more information to help you debug:
- GNOME Shell version
- Other extensions installed

It seems like the slider is initialized a few extra times, it may be conflicting with other extensions or a specific shell version :thinking:

**Comment by corebots** [comment]
Hello and sorry for the late response. I've updated(well, reinstalled) to Fedora 27 with GNOME 3.26.2 now and the above reported problem no longer appears. You can close the issue. Thank you

**Comment by kiyui** [comment]
Haha sure thing! Feel free to re-open if the issue occurs again 👍
