### ISSUE TITLE
moving the slider should enable night light

### ISSUE THREAD

**Issue by wbolster** [TimurKiyivinski/gnome-shell-night-light-slider-extension#12]
when i disable night light using the ‘disable’ menu item in the system menu dropdown (top right), the slider from this extension is still visible. this is a good thing. however, it does not do anything anymore. this is a bad thing.

my proposed solution is simple: changing the slider should re-enable night light.

**Comment by kiyui** [comment]
Hmm, this is something I can easily cater for. Will do~ :smile:

**Comment by wbolster** [comment]
awesome, thanks
