### ISSUE TITLE
"Enable always" mode is more like "enable always, except 11pm to midnight"

### ISSUE THREAD

**Issue by njsmith** [TimurKiyivinski/gnome-shell-night-light-slider-extension#14]
AFAICT, toggling the "enable always" box just sets the night light mode start/end to 00:00 and 24:00, respectively.

For some reason, what this actually seems to do is to make the screen turn gradually blue starting at ~11pm, until it's in full daylight mode at 11:59pm, and then it abruptly flips back to red-mode at 12:00am.

I'd love to have an actual "enable always" mode, but I haven't figured out how to do that. So far my workaround is to set it to manual, and enable it from 04:01 until 03:00, which at least moves the blue period outside of my normal waking hours. (For some reason you seem to need a 61 minute gap between the two settings for things to work properly? I don't understand this feature.)

**Comment by kiyui** [comment]
Hi, sorry for not getting to you earlier. What this mode does is basically the same, except with with different times. I have this issue too and am not sure how I should _efficiently_ solve it. I could have it shift the duration throughout the day as the extension is run such that the night light is always in the active time.
