### ISSUE TITLE
Option to hide night light icon?

### ISSUE THREAD

**Issue by orschiro** [TimurKiyivinski/gnome-shell-night-light-slider-extension#19]
Hey @TimurKiyivinski,

For a cleaner UI, would it be possible to add an option for these settings to hide th night light icon in the top panel? 

I actually don't need to see that if enabled always is active.

Thanks! :-)

![image](https://user-images.githubusercontent.com/170947/38035025-bc9bcc0c-32a3-11e8-8928-9210d8120624.png)

**Comment by orschiro** [comment]
@TimurKiyivinski maybe this helps?

```
const St = imports.gi.St;
const Main = imports.ui.main;


function init() {}

function enable() {
    Main.panel.statusArea.aggregateMenu._nightLight.indicators.hide()
    Main.panel.statusArea.aggregateMenu._nightLight._indicators = Main.panel.statusArea.aggregateMenu._nightLight.indicators
    //replacing it with another St.Boxlayout to avoid errors elsewhere.
    Main.panel.statusArea.aggregateMenu._nightLight.indicators = new St.BoxLayout()
}

function disable() {
    Main.panel.statusArea.aggregateMenu._nightLight.indicators.destroy()
    Main.panel.statusArea.aggregateMenu._nightLight.indicators = Main.panel.statusArea.aggregateMenu._nightLight._indicators
}
```
https://www.reddit.com/r/gnome/comments/87ihg5/is_there_a_dconfgconf_setting_or_extension_to/dwioged/?context=3

**Comment by kiyui** [comment]
Thanks, this actually does help a lot! I'll get to all the feature requests as soon as possible :smile:

**Comment by orschiro** [comment]
Great to hear! Let me know when you want more feedback :)

**Comment by orschiro** [comment]
Cannot await this to hit the extension store! Very cool.
