### ISSUE TITLE
Does nothing on Fedora

### ISSUE THREAD

**Issue by quasipedia** [TimurKiyivinski/gnome-shell-night-light-slider-extension#2]
Hi!

Is there an unstated dependency in the extension?  On fedora workstation 26 (64bit) it shows the intensity slider but the screen colour/luminosity is unaffected.

Looking at the screenshot in the README.md file I noticed that I don't have the line in the menu that says "Night Light On".  Here is midnight though. 🌃 

I like the idea of the extension though! :)

/mac

**Comment by kiyui** [comment]
Hi, you need to have night light enabled under your `Display` settings. The changes only come into effect when your night light is on. If you still have this issue with night light enabled, let me know and I'll see what I can do 😄

**Comment by quasipedia** [comment]
Ooops! 😊 
Thank you for the directions!

**Comment by kiyui** [comment]
Closing as non-issue, may make the extension auto enable night light as a user experience thing 😁

**Comment by quasipedia** [comment]
Or/And maybe just mention in the README.md perhaps?
Anyways, thanks again.  Used tonight for the first time. :)
