### ISSUE TITLE
Commands to change night light values from terminal?

### ISSUE THREAD

**Issue by orschiro** [TimurKiyivinski/gnome-shell-night-light-slider-extension#20]
Hey @TimurKiyivinski,

Related question. 

Is there a way to change the night light values with a terminal command?

Thanks already for your help!

**Comment by kiyui** [comment]
Hi, feel free to email me instead of opening issues for questions like these :slightly_smiling_face: 
You can do so with the following where `$value` is the integer value:
```bash
gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature $value
```

**Comment by orschiro** [comment]
Will do and thank you so much once more!
