### ISSUE TITLE
unable to install extension by firefox plugin neither by gnome software manager

### ISSUE THREAD

**Issue by RGNagel** [TimurKiyivinski/gnome-shell-night-light-slider-extension#24]
Hello,

I am using Gnome 3.22.2 and Debian GNU/Linux 9 (stretch) 64-bit.
When I try to install the extension in firefox by switching ON/OFF it just returns to OFF after ON is pressed. In software manager, after clicking to download and install, the install button does not disappear and the launch does not show up.
After checking

    sudo journalctl /usr/bin/gnome-shell -f

during the installation, It echoes:
- inflating this and that blabla
- extracting this and that blabla
- **JS WARNING: [/home/rgnagel/.local/share/gnome-shell/extensions/night-light-slider.timur@linux.com/extension.js 114]: in strict mode code, functions may be declared only at top level or immediately within another function**

I tried to change the function location but it brought other errors then I gave up.
Also, I did not notice any other warning/error in logs.

I will appreciate your support on that,
thanks.

**Comment by kiyui** [comment]
Hi, can you verify if the same occurs on the latest version from [here](https://github.com/TimurKiyivinski/gnome-shell-night-light-slider-extension/releases/tag/8.0)? You can install the zip from tweak tool.

If it does, perhaps you can list other extensions you have installed? I don't know if I'm doing anything non-standard, but will be happy to investigate :smile:

**Comment by RGNagel** [comment]
Hey,
I tried to install by the link you provided, however, the same warning persists and it does not get install.
Some extensions I have installed in the past:
- gnome-shell-extension-clipboard-indicator
- gnome pomodoro timer
- user theme
- Screenshot Window Sizer

I hope it helps somehow.
Thx!

**Comment by set92** [comment]
I just installed it from https://extensions.gnome.org/extension/1276/night-light-slider/, I'm using gnome 3.28.2, manjaro 64bits, and my browser is firefox 62.0a1.

I just saw this was 1 month ago, so maybe now is fixed for him too.

**Comment by RGNagel** [comment]
Hey set92,
The link you provided has the same issue. It doesn't get installed. Thx anyway.

**Comment by TheElectronWill** [comment]
The extension isn't marked as compatible with Gnome 3.22, see [metadata.json](https://github.com/TimurKiyivinski/gnome-shell-night-light-slider-extension/blob/master/night-light-slider.timur%40linux.com/metadata.json)

**Comment by kiyui** [comment]
@TheElectronWill you are a genius! Hahaha! How had I not realized this :joy: 
@RGNagel this extension requires GNOME 3.24 or later, because the night light was only introduced in that release :sweat_smile: 
https://www.gnome.org/news/2017/03/gnome-3-24-released/
