### ISSUE TITLE
Night Light being automatically re-enabled

### ISSUE THREAD

**Issue by orschiro** [TimurKiyivinski/gnome-shell-night-light-slider-extension#31]
- Latest version from the extensions page
- Disabled Night light manually from the top panel
- After a while, Night Light is being enabled again

1. Caused by this extension?
2. Can anyone else confirm this?

**Comment by kiyui** [comment]
This extension should enable the night light when logging into GNOME, or when the extension is enabled. This is intended behaviour because I was getting comments that the extension was not working, when in fact they had not enabled night light.

**Comment by orschiro** [comment]
thanks @TimurKiyivinski!

let's close this since it's an intended feature.
