### ISSUE TITLE
Add setting for brightness day/night for desktop PC

### ISSUE THREAD

**Issue by bartweber** [TimurKiyivinski/gnome-shell-night-light-slider-extension#32]
This extension is a very nice replacement for Redshift which I used to use. Only I miss a setting for the brightness at day and at night. Redshift simulates the brightness adjustment. The adjustment is gradually just like the color temperature.

**Comment by kiyui** [comment]
Hi, while it would be possible to control the device brightness (such as the laptop display), this extension will not be able to mimic the darkness the same way redshift works because it uses the built-in GNOME red-light feature.
