### ISSUE TITLE
add option to enable night light if deactivated

### ISSUE THREAD

**Issue by tristan-k** [TimurKiyivinski/gnome-shell-night-light-slider-extension#33]
Thanks for your efforts. I do have a feature request: Everytime I deactivate night light I'll have to go to the settings menu to re-enable it. I know that there is toggle for disabling it just until tomorrow but sometimes I like to disable it for some days and then enable it again. It would be neat if there was a toggle in the night light submenu to enable it if deactivated or if the submenu will not be hidden if deactivated.

**Comment by PaulCoral** [comment]
I had the problem and i did this.
https://github.com/lepaincestbon/Night-Light-Switch-Script-Gnome

**Comment by kiyui** [comment]
Closing since it is possible to just leave the night light on but set the slider all the way such that it is effectively disabled.
