### ISSUE TITLE
request(): AutomaThemely integration

### ISSUE THREAD

**Issue by haywirephoenix** [TimurKiyivinski/gnome-shell-night-light-slider-extension#47]
It would be awesome to have a toggle in the UI to also change between Light and Dark mode based on time of day, and a manual option. 

AutomaThemely can already handle theme switching based on time so it would be great to have a UI extension to enable and disable this script.

Options for the dropdown:
With AutomaThemely running, "Automatic" would be enabled, and then manual Light and Dark options. When manual option is chosen, the theme is switched and AutomaThemely stops running.

ps: You are gods for making this.

**Comment by kiyui** [comment]
Hi, thanks for mentioning [AutomaThemely](https://github.com/C2N14/AutomaThemely), that is an awesome looking app!

I'm however not quite sure I understand what your suggestion/feature request is, but it did get me wondering if AutomaThemely could be modified to run a script/command at a certain time such as the following:
```
# Enable extension
gnome-shell-extension-tool -e night-light-slider.timur@linux.com
# Disable extension
gnome-shell-extension-tool -d night-light-slider.timur@linux.com
```

If you go into the extension preferences (Run `gnome-shell-extension-prefs` in terminal) does turning the following off not work to disable the extension enough?
- Run always
- Show always

Then the time for day/night can be modified from the display settings in GNOME :smile:  

I'm happy to hear your feedback, thanks :bowing_woman:

**Comment by haywirephoenix** [comment]
Hey, thanks for your reply. I'm glad you like AutomaThemely, I forked it as I built from source for python 3.7 if you need it.

Here's an example of what I was talking about:

![nightui](https://user-images.githubusercontent.com/26271795/55655881-4485dd00-57ed-11e9-8341-0f9c73ae39e0.png)

I use both your extension and AutomaThemely and I would like to marry them together in the UI, or embed the same logic into your code. I didn't know which of you guys to come to so I've asked them aswell. Having the dark and light theme toggle in the UI sounds quite straight forward if you know what you're doing. 

It would by default, be set to Auto, which switches to the dark ui when it's night time and to light for day time. The manual modes can override this behaviour. 

Any of your wisdom would be greatly appreciated.

**Comment by kiyui** [comment]
I'm not quite sure how you did this, so perhaps you could tell me?

![automathemely buttons in night light submenu](https://user-images.githubusercontent.com/5292862/55664852-ca714a80-5824-11e9-8db4-61d70ee47617.png)

On the other hand, doing this is possible:

![slider inside the night light submenu](https://user-images.githubusercontent.com/5292862/55664877-2a67f100-5825-11e9-992b-c9202e005db4.gif)

It seems that AutomaThemely can run scripts when the time changes, so at least that is a good sign~

**Comment by kiyui** [comment]
Stale, no further comments received.
