### ISSUE TITLE
SyntaxError: illegal character

### ISSUE THREAD

**Issue by bdfish** [TimurKiyivinski/gnome-shell-night-light-slider-extension#5]
```
SyntaxError: illegal character

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
```
gnome 3.25.92
After trying manual install from source, i got the message from gnome-tweak-tool

**Comment by kiyui** [comment]
Interesting, did you install it from the compiled zip after running `make`?
If not, that is required to compile the schema for the settings.

**Comment by bdfish** [comment]
YES, I also try install from gnome extension website, neither of them working.

**Comment by kiyui** [comment]
@bdfish cool, can I have your system information so I can set up a test environment and help debug 😁 ?

**Comment by bdfish** [comment]
Debian 9 Sid.
Gnome-tweak-tool 3.25.91-1 can't launch after you install Debian Sid now, if you are going to debug, download gnome-tweak-tool from Debian testing mirror, then gnome-tweak-tool will work, someone has report this bug, maybe fix after few days. If you have less time, wait some days to fix, Debian Sid isn't stable enough now.

**Comment by kiyui** [comment]
Can't duplicate, works fine on 3.26

**Comment by seklanola** [comment]
Hello,

A have today the same problem, can anyone help me?

Regards,
Jaime Flavio Queiros

**Comment by kiyui** [comment]
@jaimeflavioqueiros am happy to help if you can specify more information about your system. I'm curious what causes this.
