### ISSUE TITLE
bug(extension): GNOME 3.34 support

### ISSUE THREAD

**Issue by Striffly** [TimurKiyivinski/gnome-shell-night-light-slider-extension#50]
**Describe the bug**
Extension does not work with GNOME Shell 3.34. 

**System Information:**
- OS: Arch Linux 5.3.4-arch1-1-ARCH
- GNOME Version: 3.34.0

**Comment by holic-cl** [comment]
Same problem here, using Debian Sid

**Comment by kiyui** [comment]
This is a duplicate of #48, 3.34 support has been released but I am unable to publish it. Again, sorry for that.

Release: https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/12.0

Just copy the files over to `~/.local/share/gnome-shell/extensions` :smile:

**Comment by holic-cl** [comment]
thanks, is working now
