### ISSUE TITLE
GNOME 3.34 version unpublished

### ISSUE THREAD

**Issue by kiyui** [TimurKiyivinski/gnome-shell-night-light-slider-extension#51]
The following bug reports have been filed wrt. the extension not working with GNOME 3.34:
- #50 
- #48 

This issue is a tracker for when I manage to publish it to the GNOME shell extensions website.

**Comment by chiawendt** [comment]
Somewhat related: night light is broken in the latest release of GNOME (3.34.1): https://www.reddit.com/r/gnome/comments/dk28oz/night_light_stop_working_after_gnome_3341/

**Comment by kiyui** [comment]
Thanks for the heads up @golopot , unfortunately I am away on holiday until the 3rd of November and won't be able to attend to any bugs until then 😄 It seems like it's something that will resolve on its own though~

**Comment by kiyui** [comment]
Looks like [FantasmicMrFox](https://extensions.gnome.org/accounts/profile/FantasmicMrFox) has helped with posting a comment regarding the state of the extension.

I've been able to update my password and upload a new version now. Will close once the review gets approved.

**Comment by abraithwaite** [comment]
Thanks @kiyui !
