### ISSUE TITLE
bug: stop working since few days ago. Light bar don't do anything.

### ISSUE THREAD

**Issue by IDKWare** [TimurKiyivinski/gnome-shell-night-light-slider-extension#56]
**Describe the bug**
Since the other day stop working on my PC. 
Doesn't matter if is ON. Don't works. I move left and right the bar, and nothing change.

I change min and max values, move again the bar. Nothing change.

I uninstalled, restarted gnome, logout and login, installed again. Nothing.

I have same OS at work, with same extensions and is working fine and fast.

**Screenshots**

**System Information:**
- OS: Ubuntu 19.04
- GNOME Version: 3.32.2

**Comment by kiyui** [comment]
Hi, could you help provide some logs or debugging information via:
```bash
journalctl /usr/bin/gnome-shell

# to filter down specifically to this extension
journalctl /usr/bin/gnome-shell | grep night-light
```

Also what version of the extension are running? Could you run:
```bash
grep version ~/.local/share/gnome-shell/extensions/night-light-slider.timur@linux.com/metadata.json
```

Thanks!

**Comment by IDKWare** [comment]
Hi, of course. 
I uploaded a .zip with both files generated, because one of them is too large.

https://1drv.ms/u/s!Agv0Eaj-WhNklCww2ArRQ8OVpVzW?e=oxaHin

Anything you need, tell me.

**Comment by IDKWare** [comment]
Hi

Excuse me, it wasn't a bug of the extension. I didn't notice before, but my Ubuntu have held broken packages what made to miss settings options and other things.

I solved that issue enabling all kind of updates for the system and your extension come to live again. 

Sorry for the inconveniences.
