### ISSUE TITLE
Isn't working in Pop OS 19.10

### ISSUE THREAD

**Issue by saikat0511** [TimurKiyivinski/gnome-shell-night-light-slider-extension#63]
Just installed and restarted gnome shell, I see the slider but it doesn't actually do anything...

**System Information:**
- OS: Pop OS 19.10
- GNOME Version: 3.34.2

**Comment by kiyui** [comment]
Hi, are you using the version of the extension published for 3.34 or the newer 3.36? Some breaking changes were introduced between the two.

**Comment by saikat0511** [comment]
uhh how to check the version?? I just installed it from extensions.gnome.org

**Comment by saikat0511** [comment]
i kinda fixed it by setting pop os's built in night light always on. Now the slider is working but sliding it to right makes it less warmer and to left makes it more warmer. Is it the expected behaviour?

**Comment by saikat0511** [comment]
Sorry I was being dumb, it works after enabling always on. Now the slider is working but sliding it to right makes it less warmer and to left makes it more warmer. Is it the expected behaviour?

**Comment by kiyui** [comment]
> right makes it less warmer and to left makes it more warmer. Is it the expected behaviour?

Yes indeed :smile:
