### ISSUE TITLE
request(): make Night Light provide "Profiles" feature

### ISSUE THREAD

**Issue by hunkjazz** [TimurKiyivinski/gnome-shell-night-light-slider-extension#65]
**Checklist:**
- [ ] I realise this extension extends on the existing GNOME night light feature and can only control the temperature.
- [x] I have gone through the extension settings to check that this feature is available.

**Feature Description:**

I'm constantly tweaking sliders because I need to set different bright and temperature combinations for work and games.

Hence, I think it would be cool to set profiles for each of them.

In addition to that, it is important for users to be able to duplicate profiles, in order to specialize them (just like classes extending classes).

**Comment by kiyui** [comment]
I was actually thinking about this, and realize that this is perhaps a better feature request for a "Profiles Manager" extension that can do more than just control the night light temperature but perhaps also control the brightness, volume, etc. of the desktop. As such, I'm closing and labelling the issue as a "wontfix" :sweat_smile:
