### ISSUE TITLE
Not working with 3.38

### ISSUE THREAD

**Issue by gllmhyt** [TimurKiyivinski/gnome-shell-night-light-slider-extension#70]
Really usefull in 3.36, since I upgraded to 3.38(.1) in both Arch Linux and Debian Testing, it's sadly not working anymore.

**System Information:**
- OS: Arch Linux and Debian Testing
- GNOME Version: 3.38(.0,.1)

**Comment by kiyui** [comment]
Hi, sorry I've only just noticed this :sweat_smile: Are you open to testing https://github.com/kiyui/gnome-shell-night-light-slider-extension/pull/68 to see if that works for you?

Note: I'm no longer on the current `master` and didn't notice!

The preferences panel still isn't functional, but I'll get that up ASAP. and spin up a 3.38 distro to test :grimacing:

**Comment by kiyui** [comment]
Hi, the new release is available [here](https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/17.0) and is currently awaiting review on the GNOME Extensions website :smile: I've confirmed it working on GNOME 3.38.1 on Arch Linux

**Comment by gllmhyt** [comment]
Tested the new release, seems to work! Nice addition with the permanent night light, thanks!

**Comment by rickhg12hs** [comment]
FYI, with `Fedora 32` using `Gnome 3.36.6`, I updated the extension via `extensions.gnome.org` and it showed an error.  Looking at the error via `lg` it cautioned that a logout/login cycle was required... not expected, but it worked!

**Comment by kiyui** [comment]
I didn't even know the new version had been reviewed and published already! I'll close this then and track that if it's a recurring issue in another thread :smile: Thanks for the reports!
