### ISSUE TITLE
Include a reset feature

### ISSUE THREAD

**Issue by jasiralavi** [TimurKiyivinski/gnome-shell-night-light-slider-extension#9]
I use this to adjust the temperature slightly while working with color sensitive stuff. It's great help.  However it would be great to allow reset to gnome level either through the extension settings or by clicking the icon next to the slider. Currently the icon sets it to the lowest level. Even better would be an option to let it toggle between custom and system defaults.

**Comment by kiyui** [comment]
Hi, I don't quite get you 😁 Do you mean you want it to toggle night light (ON/OFF) at a click of a button? If so, I can look into this

**Comment by jasiralavi** [comment]
Hi.  That would be really great if you could replace the disable functionality to an on-off toggle.  Currently 'disable' removes the night light and we need to go through the settings to enable it again. 

But what I was really looking at was a way to reset the light values to default.  I did some growling and found the default gnome setting for night time is 4000. And I had to g
Use the dconf tool to set it back to default.

**Comment by kiyui** [comment]
Hi there @jasiralavi I've not been able to get click events working on the icon to reset the night light value. Instead, there's a related issue #12 and fix #13 that might just help.

From the extension preference menu (available in tweak tool), you can set `Show Always` to true:
![screenshot from 2017-11-15 00-11-39](https://user-images.githubusercontent.com/5292862/32790525-a4331b52-c999-11e7-8caa-3d6646d8dfed.png)

Also, by changing the `Maximum Value` to 4000, you can always slide all the way to the right to disable the red-shifted colours.

**Comment by jasiralavi** [comment]
Thank you so much. Another option would be to mark the default night value
(4000) and the default day value on the slider and enable a slight snap
action to help users to quickly reset to these values. That would work
brilliantly with this new fix that you have released. Thanks again!

**Comment by kiyui** [comment]
Stale issue, some of this has changed with the [latest release](https://github.com/kiyui/gnome-shell-night-light-slider-extension/releases/tag/17.0).
